# Generated by Django 3.2.18 on 2023-10-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0002_auto_20230416_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodboard',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moodboard',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moodboard',
            name='stock_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='moodboard_images'),
        ),
    ]
