# Generated by Django 3.2.18 on 2023-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0003_auto_20231016_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
    ]
