# Generated by Django 3.2.18 on 2023-10-20 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodboard',
            name='listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moodboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
