# Generated by Django 3.2.18 on 2023-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0006_moodboard_listed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodboard',
            name='listed_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
